### ISSUE TITLE
Improper option values

### ISSUE THREAD

**Issue by tissatussa** [Gourab-Ghosh/timecat-rs#1]
I just compiled your v1.35.1 and it runs fine in CuteChess GUI, but i can't set `Hash` and `Move Overhead` because their `max` values are too big :

![timecat-options](https://github.com/user-attachments/assets/5f11e430-e2ae-4403-aec7-5f9fd7138dea)

![timecat-options2](https://github.com/user-attachments/assets/86c497b0-7375-4f2b-922b-9115320f7f15)

Is this intentional ? I guess not ..

[ i'm on Xubuntu 22.04 ]

**Comment by Gourab-Ghosh** [comment]
> I just compiled your v1.35.1 and it runs fine in CuteChess GUI, but i can't set `Hash` and `Move Overhead` because their `max` values are too big :
> 
> ![timecat-options](https://private-user-images.githubusercontent.com/1109281/365390842-5f11e430-e2ae-4403-aec7-5f9fd7138dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODAzNDgsIm5iZiI6MTcyNTc4MDA0OCwicGF0aCI6Ii8xMTA5MjgxLzM2NTM5MDg0Mi01ZjExZTQzMC1lMmFlLTQ0MDMtYWVjNy01ZjlmZDcxMzhkZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMDcyMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjJiMjkyOTM1ZWE4ZDMxZWU4Mjc4ZjQ2MzY5NjU1YzYyMDFiNWJkYTEzYTg5Y2Y2ZjNhODVkNTIxMGQ5MDNlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Er2zSm5uuOLWJq-VnB3cmfFRdZ_ImL4V5hurq2UOW9s)
> 
> ![timecat-options2](https://private-user-images.githubusercontent.com/1109281/365390849-86c497b0-7375-4f2b-922b-9115320f7f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODAzNDgsIm5iZiI6MTcyNTc4MDA0OCwicGF0aCI6Ii8xMTA5MjgxLzM2NTM5MDg0OS04NmM0OTdiMC03Mzc1LTRmMmItOTIyYi05MTE1MzIwZjdmMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMDcyMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTc5YzY1MGY4NzY1YjdhNzI5MDU4Mzg4MTRiMmM3OTJkMzA2OGZiYjRiNDhmZDJlYWUwMTQxMTdiYjJlYzQ2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JubCPzEFsxoZFI1q7q-EPtlN0B2JiR6IpN5lH9UhM9A)
> 
> Is this intentional ? I guess not ..
> 
> [ i'm on Xubuntu 22.04 ]

Thank you for letteing me know about this. Previously I had tried to make the values as big as possible. Now I think I have to reduce them to make it work.

**Comment by Gourab-Ghosh** [comment]
This has been fixed.

**Comment by tissatussa** [comment]
Solved ! :+1:
