### ISSUE TITLE
wrong eval sign

### ISSUE THREAD

**Issue by tissatussa** [Gourab-Ghosh/timecat-rs#2]
Timecat (v1.35.1) seems to display the evaluation values with a wrong sign. These values should reflect how good the engine thinks its own position is, but Timecat shows wrong signs, see these screenshots.

Here Timecat lost with White. Indeed it displays negative values, except for the M(ate) values, which are positive :

![timecat-lost-with-white](https://github.com/user-attachments/assets/570124f5-1ee8-429a-af9e-c9ad07edf61b)

Here Timecat won with Black, so its values should have been positive :

![timecat-won-with-black](https://github.com/user-attachments/assets/6ad321f5-2d0a-43cf-a123-9e9602ae9d50)

**Comment by Gourab-Ghosh** [comment]
> Timecat (v1.35.1) seems to display the evaluation values with a wrong sign. These values should reflect how good the engine thinks its own position is, but Timecat shows wrong signs, see these screenshots.
> 
> Here Timecat lost with White. Indeed it displays negative values, except for the M(ate) values, which are positive :
> 
> ![timecat-lost-with-white](https://private-user-images.githubusercontent.com/1109281/365400085-570124f5-1ee8-429a-af9e-c9ad07edf61b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODA3MzQsIm5iZiI6MTcyNTc4MDQzNCwicGF0aCI6Ii8xMTA5MjgxLzM2NTQwMDA4NS01NzAxMjRmNS0xZWU4LTQyOWEtYWY5ZS1jOWFkMDdlZGY2MWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMDcyNzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQzZWQ5ODFiOGM0NzU5YzEyZDgwNjhjZTc3NGRhYThiOTkzYWJhNzk0OTc5NDljNDA3ZGEyMzRiZmRiMzY1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kTmDRi8kwAzicfFgpCXCHzEaT6ANS6A6du5yt926Yi8)
> 
> Here Timecat won with Black, so its values should have been positive :
> 
> ![timecat-won-with-black](https://private-user-images.githubusercontent.com/1109281/365400097-6ad321f5-2d0a-43cf-a123-9e9602ae9d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODA3MzQsIm5iZiI6MTcyNTc4MDQzNCwicGF0aCI6Ii8xMTA5MjgxLzM2NTQwMDA5Ny02YWQzMjFmNS0yZDBhLTQzY2YtYTEyMy05ZTk2MDJhZTlkNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMDcyNzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmI5MDE0MTYyODM2MjNlMzcxODM5NmY0Y2U2YzJlYzEwYzIwZGQ1ODg3YWU4NjExNjE5NmM4N2FkNTk3NjI1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7ooT8JaSfo1MjhIO30KoLNw26HMre3jen-feWwT2sak)

Thank you for letting me know. I will take a look into this.

**Comment by Gourab-Ghosh** [comment]
This has been fixed. Feel free to test this again and report bugs if found..

**Comment by tissatussa** [comment]
@Gourab-Ghosh indeed it works now, simply great :+1:
